import { DiagramSpec, DiagramType } from '../types';

/**
 * Builds or customizes crisp, mathematically consistent SVGs for STEM questions.
 * Handles circuits, mechanics, ray optics, geometry, graphs, chemistry, and biology.
 */
export function generateDiagramSvg(type: DiagramType, params: Record<string, string | number> = {}): DiagramSpec {
  // If a full custom SVG was generated by AI, validate and use it directly
  if (params.customSvgCode && typeof params.customSvgCode === 'string' && params.customSvgCode.includes('<svg')) {
    return {
      type,
      title: String(params.title || `${type.replace(/_/g, ' ')} Diagram`),
      svgCode: String(params.customSvgCode).trim(),
      parameters: params,
      labels: Array.isArray(params.labels) ? params.labels : ['Figure 1'],
      caption: String(params.caption || `Diagram illustrating ${type.replace(/_/g, ' ')}.`)
    };
  }

  switch (type) {
    case 'circuit':
      return createCircuitDiagram(params);
    case 'mechanics_fbd':
      return createMechanicsDiagram(params);
    case 'ray_optics':
      return createRayOpticsDiagram(params);
    case 'graph_kinematics':
      return createKinematicsGraph(params);
    case 'thermo_pv':
      return createPvDiagram(params);
    case 'geometry':
      return createGeometryDiagram(params);
    case 'chemistry_organic':
      return createChemistryDiagram(params);
    case 'biology_cell':
      return createBiologyDiagram(params);
    default:
      return {
        type: 'none',
        title: 'No Diagram Required',
        svgCode: '',
        parameters: {},
        labels: [],
        caption: ''
      };
  }
}

function createCircuitDiagram(params: Record<string, any>): DiagramSpec {
  const r1 = params.r1 || '8 Ω';
  const r2 = params.r2 || '8 Ω';
  const r3 = params.r3 || '6 Ω';
  const voltage = params.voltage || '30 V';

  const svg = `
<svg viewBox="0 0 540 290" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <filter id="circ-shadow" x="-5%" y="-5%" width="110%" height="110%">
      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-opacity="0.06"/>
    </filter>
    <marker id="circ-arrow" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#ea580c"/>
    </marker>
  </defs>

  <!-- Background panel with subtle engineering grid -->
  <rect width="540" height="290" rx="12" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1.5" />
  <pattern id="grid-pattern" width="20" height="20" patternUnits="userSpaceOnUse">
    <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#f1f5f9" stroke-width="1"/>
  </pattern>
  <rect width="540" height="290" rx="12" fill="url(#grid-pattern)" />

  <!-- Outer Wires & Circuit Loop -->
  <!-- Left DC Battery Source -->
  <line x1="60" y1="110" x2="60" y2="165" stroke="#2563eb" stroke-width="4.5" stroke-linecap="round"/>
  <line x1="44" y1="122" x2="44" y2="153" stroke="#64748b" stroke-width="3" stroke-linecap="round"/>
  
  <!-- Battery Polarity Signs -->
  <circle cx="60" cy="94" r="9" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1.5"/>
  <text x="60" y="98" font-size="12" font-weight="900" fill="#2563eb" text-anchor="middle">+</text>
  <circle cx="44" cy="172" r="9" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1.5"/>
  <text x="44" y="176" font-size="12" font-weight="900" fill="#64748b" text-anchor="middle">−</text>

  <!-- Voltage Label Badge -->
  <rect x="18" y="125" width="56" height="24" rx="5" fill="#ffffff" stroke="#2563eb" stroke-width="1.5" filter="url(#circ-shadow)"/>
  <text x="46" y="141" font-size="12" font-weight="bold" fill="#1e40af" text-anchor="middle">V = ${voltage}</text>

  <!-- Upper Wire: Battery to Node A -->
  <path d="M 60 110 L 60 65 L 180 65" fill="none" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>
  <!-- Total Current Flow Arrow -->
  <line x1="95" y1="65" x2="135" y2="65" stroke="#ea580c" stroke-width="2.5" marker-end="url(#circ-arrow)"/>
  <rect x="100" y="44" width="50" height="18" rx="4" fill="#fff7ed" stroke="#fed7aa" stroke-width="1"/>
  <text x="125" y="57" font-size="10" font-weight="bold" fill="#c2410c" text-anchor="middle">Total I</text>

  <!-- Node A Junction -->
  <circle cx="180" cy="65" r="5" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <rect x="155" y="32" width="52" height="20" rx="4" fill="#fef2f2" stroke="#fecaca" stroke-width="1"/>
  <text x="181" y="46" font-size="11" font-weight="bold" fill="#dc2626" text-anchor="middle">Node A</text>

  <!-- Parallel Branch 1: Top Resistor R1 -->
  <!-- Wire from Node A into R1 -->
  <path d="M 180 65 L 210 65" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>
  <!-- Resistor 1 Zigzag -->
  <path d="M 210 65 L 220 50 L 230 80 L 240 50 L 250 80 L 260 50 L 270 80 L 280 65 L 310 65" fill="none" stroke="#0f172a" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
  <!-- Branch 1 Current Arrow -->
  <line x1="240" y1="36" x2="265" y2="36" stroke="#ea580c" stroke-width="2" marker-end="url(#circ-arrow)"/>
  <text x="252" y="28" font-size="10" font-weight="bold" fill="#ea580c" text-anchor="middle">I₁</text>
  <!-- R1 Label Badge -->
  <rect x="230" y="88" width="80" height="22" rx="5" fill="#eff6ff" stroke="#93c5fd" stroke-width="1.5" filter="url(#circ-shadow)"/>
  <text x="270" y="103" font-size="11" font-weight="bold" fill="#1d4ed8" text-anchor="middle">R₁ = ${r1}</text>

  <!-- Parallel Branch 2: Lower Resistor R2 -->
  <path d="M 180 65 L 180 155 L 210 155" fill="none" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>
  <!-- Resistor 2 Zigzag -->
  <path d="M 210 155 L 220 140 L 230 170 L 240 140 L 250 170 L 260 140 L 270 170 L 280 155 L 310 155" fill="none" stroke="#0f172a" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
  <!-- Branch 2 Current Arrow -->
  <line x1="240" y1="126" x2="265" y2="126" stroke="#ea580c" stroke-width="2" marker-end="url(#circ-arrow)"/>
  <text x="252" y="118" font-size="10" font-weight="bold" fill="#ea580c" text-anchor="middle">I₂</text>
  <!-- R2 Label Badge -->
  <rect x="230" y="178" width="80" height="22" rx="5" fill="#eff6ff" stroke="#93c5fd" stroke-width="1.5" filter="url(#circ-shadow)"/>
  <text x="270" y="193" font-size="11" font-weight="bold" fill="#1d4ed8" text-anchor="middle">R₂ = ${r2}</text>

  <!-- Reconnect Lower Branch to Node B -->
  <path d="M 310 155 L 340 155 L 340 65" fill="none" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>
  <path d="M 310 65 L 340 65" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>

  <!-- Node B Junction -->
  <circle cx="340" cy="65" r="5" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <rect x="315" y="32" width="52" height="20" rx="4" fill="#fef2f2" stroke="#fecaca" stroke-width="1"/>
  <text x="341" y="46" font-size="11" font-weight="bold" fill="#dc2626" text-anchor="middle">Node B</text>

  <!-- Series Resistor R3 -->
  <path d="M 340 65 L 370 65" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>
  <path d="M 370 65 L 380 50 L 390 80 L 400 50 L 410 80 L 420 50 L 430 80 L 440 65 L 470 65" fill="none" stroke="#0f172a" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
  <!-- R3 Label Badge -->
  <rect x="390" y="88" width="80" height="22" rx="5" fill="#f0fdf4" stroke="#86efac" stroke-width="1.5" filter="url(#circ-shadow)"/>
  <text x="430" y="103" font-size="11" font-weight="bold" fill="#15803d" text-anchor="middle">R₃ = ${r3}</text>

  <!-- Return Loop Wire (Right to Bottom to Battery Negative) -->
  <path d="M 470 65 L 470 230 L 44 230 L 44 153" fill="none" stroke="#0f172a" stroke-width="3" stroke-linecap="round"/>

  <!-- Return Current Arrow -->
  <line x1="280" y1="230" x2="240" y2="230" stroke="#ea580c" stroke-width="2.5" marker-end="url(#circ-arrow)"/>
  <text x="260" y="248" font-size="11" font-weight="bold" fill="#c2410c" text-anchor="middle">Return Current I</text>

  <!-- Ground Reference Symbol -->
  <line x1="260" y1="230" x2="260" y2="252" stroke="#64748b" stroke-width="2"/>
  <line x1="248" y1="252" x2="272" y2="252" stroke="#64748b" stroke-width="3"/>
  <line x1="252" y1="257" x2="268" y2="257" stroke="#64748b" stroke-width="2"/>
  <line x1="256" y1="262" x2="264" y2="262" stroke="#64748b" stroke-width="1.5"/>
</svg>
`;

  return {
    type: 'circuit',
    title: 'DC Resistor Network Schematic',
    svgCode: svg.trim(),
    parameters: { r1, r2, r3, voltage },
    labels: ['R₁ (Parallel)', 'R₂ (Parallel)', 'R₃ (Series)', 'Node A', 'Node B', 'DC Source V', 'Current I'],
    caption: `Schematic diagram showing parallel combination of R₁ (${r1}) and R₂ (${r2}) connected at Node A and Node B, in series with R₃ (${r3}) across a ${voltage} DC supply.`
  };
}

function createMechanicsDiagram(params: Record<string, any>): DiagramSpec {
  const theta = params.theta || '30°';
  const m1 = params.m1 || '6 kg';
  const m2 = params.m2 || '4 kg';
  const mu = params.mu !== undefined ? params.mu : '0.2';

  const svg = `
<svg viewBox="0 0 540 310" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <marker id="fbd-arrow-green" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#10b981"/>
    </marker>
    <marker id="fbd-arrow-red" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#dc2626"/>
    </marker>
    <marker id="fbd-arrow-amber" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#f59e0b"/>
    </marker>
  </defs>

  <!-- Background Panel -->
  <rect width="540" height="310" rx="12" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1.5" />

  <!-- Ground Reference Surface with Hatch Marks -->
  <line x1="30" y1="260" x2="500" y2="260" stroke="#334155" stroke-width="3"/>
  <path d="M 40 260 L 30 272 M 70 260 L 60 272 M 100 260 L 90 272 M 130 260 L 120 272 M 160 260 L 150 272 M 190 260 L 180 272 M 220 260 L 210 272 M 250 260 L 240 272 M 280 260 L 270 272 M 310 260 L 300 272 M 340 260 L 330 272 M 370 260 L 360 272 M 400 260 L 390 272 M 430 260 L 420 272 M 460 260 L 450 272 M 490 260 L 480 272" stroke="#94a3b8" stroke-width="1.5"/>

  <!-- Incline Plane Triangle (Wedge) -->
  <polygon points="50,260 370,260 370,80" fill="#f1f5f9" stroke="#1e293b" stroke-width="3.5" stroke-linejoin="round"/>

  <!-- Angle arc θ -->
  <path d="M 120 260 A 70 70 0 0 0 112 225" fill="none" stroke="#2563eb" stroke-width="2.5"/>
  <rect x="126" y="232" width="60" height="22" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
  <text x="156" y="247" font-size="12" font-weight="bold" fill="#1d4ed8" text-anchor="middle">θ = ${theta}</text>

  <!-- Frictionless Pulley at Incline Apex -->
  <!-- Pulley mount bracket -->
  <line x1="370" y1="80" x2="385" y2="65" stroke="#475569" stroke-width="4" stroke-linecap="round"/>
  <!-- Pulley Wheel -->
  <circle cx="385" cy="65" r="18" fill="#e2e8f0" stroke="#1e293b" stroke-width="3"/>
  <circle cx="385" cy="65" r="5" fill="#3b82f6"/>

  <!-- Incline Mass Block m1 (Rotated along incline θ approx 29.35°) -->
  <g transform="translate(205, 172) rotate(-29.35)">
    <!-- Block Body -->
    <rect x="-40" y="-40" width="80" height="40" rx="4" fill="#3b82f6" stroke="#1d4ed8" stroke-width="2.5"/>
    <text x="0" y="-15" font-size="13" font-weight="bold" fill="#ffffff" text-anchor="middle">m₁ = ${m1}</text>

    <!-- Normal Force Vector N (Perpendicular to Incline) -->
    <line x1="0" y1="-40" x2="0" y2="-90" stroke="#10b981" stroke-width="2.5" marker-end="url(#fbd-arrow-green)"/>
    <rect x="-14" y="-108" width="28" height="18" rx="3" fill="#ecfdf5" stroke="#a7f3d0" stroke-width="1"/>
    <text x="0" y="-95" font-size="11" font-weight="bold" fill="#047857" text-anchor="middle">N</text>

    <!-- Friction Vector f_k (Down or up incline) -->
    <line x1="-40" y1="0" x2="-85" y2="0" stroke="#dc2626" stroke-width="2.5" marker-end="url(#fbd-arrow-red)"/>
    <text x="-75" y="-8" font-size="10" font-weight="bold" fill="#b91c1c">fₖ (μ=${mu})</text>

    <!-- Cord Tension Vector T (Toward pulley) -->
    <line x1="40" y1="-18" x2="95" y2="-18" stroke="#f59e0b" stroke-width="2.5" marker-end="url(#fbd-arrow-amber)"/>
    <text x="75" y="-28" font-size="11" font-weight="bold" fill="#b45309">T</text>

    <!-- Gravity Vector decomposed straight down -->
    <line x1="0" y1="0" x2="35" y2="60" stroke="#dc2626" stroke-width="2.5" marker-end="url(#fbd-arrow-red)"/>
    <text x="45" y="70" font-size="11" font-weight="bold" fill="#dc2626">m₁g</text>
  </g>

  <!-- Massless String connecting m1 over Pulley to m2 -->
  <line x1="240" y1="152" x2="385" y2="47" stroke="#0f172a" stroke-width="3"/>
  <line x1="403" y1="65" x2="403" y2="160" stroke="#0f172a" stroke-width="3"/>

  <!-- Hanging Mass Block m2 -->
  <rect x="381" y="160" width="44" height="44" rx="5" fill="#8b5cf6" stroke="#6d28d9" stroke-width="2.5"/>
  <text x="403" y="184" font-size="12" font-weight="bold" fill="#ffffff" text-anchor="middle">m₂</text>
  <text x="403" y="198" font-size="10" font-weight="bold" fill="#ffffff" text-anchor="middle">${m2}</text>

  <!-- Hanging Tension T Vector Upward -->
  <line x1="403" y1="160" x2="403" y2="120" stroke="#f59e0b" stroke-width="2.5" marker-end="url(#fbd-arrow-amber)"/>
  <text x="415" y="138" font-size="11" font-weight="bold" fill="#b45309">T</text>

  <!-- Hanging Gravity m2g Vector Downward -->
  <line x1="403" y1="204" x2="403" y2="246" stroke="#dc2626" stroke-width="2.5" marker-end="url(#fbd-arrow-red)"/>
  <text x="418" y="240" font-size="11" font-weight="bold" fill="#dc2626">m₂g</text>
</svg>
`;

  return {
    type: 'mechanics_fbd',
    title: 'Inclined Plane & Pulley Free-Body Diagram',
    svgCode: svg.trim(),
    parameters: { theta, m1, m2, mu },
    labels: ['Mass m₁ (Incline)', 'Mass m₂ (Hanging)', 'Normal Force N', 'Tension T', 'Friction fₖ', 'Incline Angle θ'],
    caption: `Free-body schematic of mass m₁ (${m1}) on an inclined plane of inclination θ = ${theta} (friction coefficient μ = ${mu}) connected over a frictionless pulley to hanging mass m₂ (${m2}).`
  };
}

function createRayOpticsDiagram(params: Record<string, any>): DiagramSpec {
  const f = params.f || '20 cm';
  const u = params.u || '30 cm';
  const v = params.v || '60 cm';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <marker id="ray-arrow-red" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#f43f5e"/>
    </marker>
    <marker id="ray-arrow-purple" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#a855f7"/>
    </marker>
  </defs>

  <!-- Engineering Optical Bench Dark Canvas -->
  <rect width="540" height="270" rx="12" fill="#0f172a" stroke="#1e293b" stroke-width="1.5" />

  <!-- Principal Optical Axis -->
  <line x1="20" y1="135" x2="520" y2="135" stroke="#475569" stroke-width="2" stroke-dasharray="8,5"/>
  <text x="510" y="125" font-size="11" font-weight="bold" fill="#94a3b8">Principal Axis</text>

  <!-- Convex Lens (Refracting Interface) at x = 270 -->
  <path d="M 270 30 Q 295 135 270 240 Q 245 135 270 30" fill="rgba(56, 189, 248, 0.18)" stroke="#38bdf8" stroke-width="2.5"/>
  <line x1="270" y1="20" x2="270" y2="250" stroke="#38bdf8" stroke-width="1.5" stroke-dasharray="4,4"/>

  <!-- Optical Center (O) -->
  <circle cx="270" cy="135" r="4" fill="#ffffff"/>
  <text x="265" y="152" font-size="12" font-weight="bold" fill="#e2e8f0">O</text>

  <!-- Focal and 2F Markers -->
  <!-- Left Side: F1 at x=190, 2F1 at x=110 -->
  <circle cx="190" cy="135" r="3.5" fill="#fbbf24"/>
  <text x="186" y="154" font-size="11" font-weight="bold" fill="#f59e0b">F₁</text>
  <circle cx="110" cy="135" r="3.5" fill="#fbbf24"/>
  <text x="102" y="154" font-size="11" font-weight="bold" fill="#f59e0b">2F₁</text>

  <!-- Right Side: F2 at x=350, 2F2 at x=430 -->
  <circle cx="350" cy="135" r="3.5" fill="#fbbf24"/>
  <text x="346" y="154" font-size="11" font-weight="bold" fill="#f59e0b">F₂</text>
  <circle cx="430" cy="135" r="3.5" fill="#fbbf24"/>
  <text x="422" y="154" font-size="11" font-weight="bold" fill="#f59e0b">2F₂</text>

  <!-- Upright Object Arrow AB between F1 and 2F1 (x = 150, height = 55) -->
  <line x1="150" y1="135" x2="150" y2="80" stroke="#4ade80" stroke-width="3.5"/>
  <polygon points="150,72 145,84 155,84" fill="#4ade80"/>
  <text x="145" y="68" font-size="12" font-weight="bold" fill="#4ade80">A</text>
  <text x="145" y="152" font-size="11" font-weight="bold" fill="#86efac">B (Object)</text>

  <!-- Ray 1: Parallel to Axis -> Refracts through F2 -->
  <line x1="150" y1="80" x2="270" y2="80" stroke="#f43f5e" stroke-width="2"/>
  <line x1="200" y1="80" x2="215" y2="80" stroke="#f43f5e" stroke-width="2" marker-end="url(#ray-arrow-red)"/>
  <line x1="270" y1="80" x2="450" y2="202.5" stroke="#f43f5e" stroke-width="2"/>
  <line x1="330" y1="121" x2="350" y2="135" stroke="#f43f5e" stroke-width="2" marker-end="url(#ray-arrow-red)"/>

  <!-- Ray 2: Passing straight through Optical Center O undeflected -->
  <line x1="150" y1="80" x2="450" y2="202.5" stroke="#a855f7" stroke-width="2"/>
  <line x1="200" y1="100.5" x2="220" y2="108.7" stroke="#a855f7" stroke-width="2" marker-end="url(#ray-arrow-purple)"/>

  <!-- Real Inverted Magnified Image A'B' at Intersection (x = 450, y = 202.5) -->
  <line x1="450" y1="135" x2="450" y2="202.5" stroke="#38bdf8" stroke-width="3.5"/>
  <polygon points="450,210 445,198 455,198" fill="#38bdf8"/>
  <text x="456" y="215" font-size="12" font-weight="bold" fill="#38bdf8">A' (Image)</text>
  <text x="456" y="152" font-size="11" font-weight="bold" fill="#7dd3fc">B'</text>

  <!-- Dimension Indicator Brackets -->
  <!-- Object distance u -->
  <line x1="150" y1="230" x2="270" y2="230" stroke="#94a3b8" stroke-width="1.5"/>
  <line x1="150" y1="225" x2="150" y2="235" stroke="#94a3b8" stroke-width="1.5"/>
  <line x1="270" y1="225" x2="270" y2="235" stroke="#94a3b8" stroke-width="1.5"/>
  <text x="210" y="244" font-size="11" font-weight="bold" fill="#cbd5e1" text-anchor="middle">u = -${u}</text>

  <!-- Focal Length f -->
  <line x1="270" y1="255" x2="350" y2="255" stroke="#fbbf24" stroke-width="1.5"/>
  <line x1="270" y1="250" x2="270" y2="260" stroke="#fbbf24" stroke-width="1.5"/>
  <line x1="350" y1="250" x2="350" y2="260" stroke="#fbbf24" stroke-width="1.5"/>
  <text x="310" y="265" font-size="11" font-weight="bold" fill="#fbbf24" text-anchor="middle">f = +${f}</text>
</svg>
`;

  return {
    type: 'ray_optics',
    title: 'Convex Lens Image Formation Ray Diagram',
    svgCode: svg.trim(),
    parameters: { f, u, v },
    labels: ['Object AB', 'Real Inverted Image A\'B\'', 'Focal Length f', 'Object Distance u', 'Image Distance v', 'Optical Center O'],
    caption: `Precision ray diagram for a thin convex lens of focal length f = ${f} with object placed at u = ${u}, forming an inverted real image at distance v = ${v}.`
  };
}

function createKinematicsGraph(params: Record<string, any>): DiagramSpec {
  const vMax = params.vMax || '20 m/s';
  const tTotal = params.tTotal || '10 s';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <marker id="axis-arrow" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#0f172a"/>
    </marker>
  </defs>

  <rect width="540" height="270" rx="12" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5" />

  <!-- Grid lines -->
  <line x1="70" y1="180" x2="490" y2="180" stroke="#f1f5f9" stroke-width="1.5"/>
  <line x1="70" y1="120" x2="490" y2="120" stroke="#f1f5f9" stroke-width="1.5"/>
  <line x1="70" y1="65" x2="490" y2="65" stroke="#f1f5f9" stroke-width="1.5"/>
  <line x1="180" y1="30" x2="180" y2="220" stroke="#f1f5f9" stroke-width="1.5"/>
  <line x1="360" y1="30" x2="360" y2="220" stroke="#f1f5f9" stroke-width="1.5"/>
  <line x1="450" y1="30" x2="450" y2="220" stroke="#f1f5f9" stroke-width="1.5"/>

  <!-- Shaded Area (Displacement) -->
  <polygon points="70,220 180,65 360,65 450,220" fill="rgba(37, 99, 235, 0.12)"/>

  <!-- Axes -->
  <!-- Horizontal Time Axis -->
  <line x1="70" y1="220" x2="490" y2="220" stroke="#0f172a" stroke-width="2.5" marker-end="url(#axis-arrow)"/>
  <text x="470" y="245" font-size="12" font-weight="bold" fill="#0f172a">Time t (s)</text>

  <!-- Vertical Velocity Axis -->
  <line x1="70" y1="220" x2="70" y2="25" stroke="#0f172a" stroke-width="2.5" marker-end="url(#axis-arrow)"/>
  <text x="25" y="25" font-size="12" font-weight="bold" fill="#0f172a">v (m/s)</text>

  <!-- Trapezoidal v-t Profile Curve -->
  <polyline points="70,220 180,65 360,65 450,220" fill="none" stroke="#2563eb" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/>

  <!-- Drop Lines to Axes -->
  <line x1="180" y1="65" x2="180" y2="220" stroke="#94a3b8" stroke-width="1.5" stroke-dasharray="4,4"/>
  <line x1="360" y1="65" x2="360" y2="220" stroke="#94a3b8" stroke-width="1.5" stroke-dasharray="4,4"/>
  <line x1="70" y1="65" x2="180" y2="65" stroke="#94a3b8" stroke-width="1.5" stroke-dasharray="4,4"/>

  <!-- Ticks and Values -->
  <text x="60" y="224" font-size="12" font-weight="bold" fill="#64748b" text-anchor="end">0</text>
  <rect x="15" y="54" width="50" height="22" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
  <text x="40" y="69" font-size="11" font-weight="bold" fill="#1d4ed8" text-anchor="middle">${vMax}</text>

  <text x="180" y="238" font-size="11" font-weight="bold" fill="#475569" text-anchor="middle">t₁ = 2 s</text>
  <text x="360" y="238" font-size="11" font-weight="bold" fill="#475569" text-anchor="middle">t₂ = 7 s</text>
  <rect x="425" y="225" width="50" height="22" rx="4" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1"/>
  <text x="450" y="240" font-size="11" font-weight="bold" fill="#0f172a" text-anchor="middle">T = ${tTotal}</text>

  <!-- Stage Phase Badges -->
  <rect x="100" y="130" width="75" height="20" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
  <text x="137" y="144" font-size="10" font-weight="bold" fill="#2563eb" text-anchor="middle">Acceleration</text>

  <rect x="235" y="40" width="80" height="20" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
  <text x="275" y="54" font-size="10" font-weight="bold" fill="#1e40af" text-anchor="middle">Constant v</text>

  <rect x="380" y="130" width="75" height="20" rx="4" fill="#fef2f2" stroke="#fecaca" stroke-width="1"/>
  <text x="417" y="144" font-size="10" font-weight="bold" fill="#dc2626" text-anchor="middle">Deceleration</text>

  <!-- Area Callout Badge -->
  <rect x="210" y="145" width="130" height="24" rx="5" fill="#ffffff" stroke="#2563eb" stroke-width="1.5"/>
  <text x="275" y="161" font-size="11" font-weight="bold" fill="#1e40af" text-anchor="middle">Displacement s = ∫ v dt</text>
</svg>
`;

  return {
    type: 'graph_kinematics',
    title: 'Velocity-Time (v-t) Kinematics Graph',
    svgCode: svg.trim(),
    parameters: { vMax, tTotal },
    labels: ['Maximum Velocity vMax', 'Total Time T', 'Acceleration Phase', 'Uniform Velocity Phase', 'Deceleration Phase', 'Displacement Area'],
    caption: `Motion profile graph demonstrating linear acceleration to peak velocity ${vMax}, uniform speed phase, and constant deceleration to rest at total time T = ${tTotal}.`
  };
}

function createPvDiagram(params: Record<string, any>): DiagramSpec {
  const p1 = params.p1 || '4 atm';
  const v1 = params.v1 || '1 L';
  const p2 = params.p2 || '1 atm';
  const v2 = params.v2 || '4 L';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <marker id="pv-arrow-red" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#dc2626"/>
    </marker>
    <marker id="pv-arrow-blue" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#2563eb"/>
    </marker>
    <marker id="pv-axis" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#0f172a"/>
    </marker>
  </defs>

  <rect width="540" height="270" rx="12" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1.5" />

  <!-- Axes -->
  <line x1="80" y1="220" x2="490" y2="220" stroke="#0f172a" stroke-width="2.5" marker-end="url(#pv-axis)"/>
  <text x="460" y="245" font-size="12" font-weight="bold" fill="#0f172a">Volume V (L)</text>

  <line x1="80" y1="220" x2="80" y2="25" stroke="#0f172a" stroke-width="2.5" marker-end="url(#pv-axis)"/>
  <text x="25" y="30" font-size="12" font-weight="bold" fill="#0f172a">P (atm)</text>

  <!-- Enclosed Cyclic Area (Work Done) -->
  <polygon points="150,75 380,75 380,185 150,185" fill="rgba(245, 158, 11, 0.15)"/>

  <!-- Path A -> B (Isobaric Expansion) -->
  <line x1="150" y1="75" x2="380" y2="75" stroke="#dc2626" stroke-width="3"/>
  <line x1="250" y1="75" x2="275" y2="75" stroke="#dc2626" stroke-width="3" marker-end="url(#pv-arrow-red)"/>
  <text x="265" y="65" font-size="10" font-weight="bold" fill="#dc2626" text-anchor="middle">Isobaric Expansion</text>

  <!-- Path B -> C (Isochoric Depressurization) -->
  <line x1="380" y1="75" x2="380" y2="185" stroke="#2563eb" stroke-width="3"/>
  <line x1="380" y1="120" x2="380" y2="140" stroke="#2563eb" stroke-width="3" marker-end="url(#pv-arrow-blue)"/>
  <text x="445" y="135" font-size="10" font-weight="bold" fill="#2563eb" text-anchor="middle">Isochoric Cooling</text>

  <!-- Path C -> D (Isobaric Compression) -->
  <line x1="380" y1="185" x2="150" y2="185" stroke="#16a34a" stroke-width="3"/>
  <line x1="275" y1="185" x2="250" y2="185" stroke="#16a34a" stroke-width="3" marker-end="url(#pv-arrow-blue)"/>
  <text x="265" y="202" font-size="10" font-weight="bold" fill="#16a34a" text-anchor="middle">Isobaric Compression</text>

  <!-- Path D -> A (Isochoric Heating) -->
  <line x1="150" y1="185" x2="150" y2="75" stroke="#9333ea" stroke-width="3"/>
  <line x1="150" y1="140" x2="150" y2="120" stroke="#9333ea" stroke-width="3" marker-end="url(#pv-arrow-red)"/>
  <text x="95" y="135" font-size="10" font-weight="bold" fill="#9333ea" text-anchor="middle">Isochoric</text>

  <!-- State Points & Coordinates -->
  <circle cx="150" cy="75" r="5.5" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <text x="135" y="65" font-size="12" font-weight="bold" fill="#b91c1c">A (${p1}, ${v1})</text>

  <circle cx="380" cy="75" r="5.5" fill="#2563eb" stroke="#ffffff" stroke-width="2"/>
  <text x="390" y="70" font-size="12" font-weight="bold" fill="#1d4ed8">B (${p1}, ${v2})</text>

  <circle cx="380" cy="185" r="5.5" fill="#16a34a" stroke="#ffffff" stroke-width="2"/>
  <text x="390" y="195" font-size="12" font-weight="bold" fill="#15803d">C (${p2}, ${v2})</text>

  <circle cx="150" cy="185" r="5.5" fill="#9333ea" stroke="#ffffff" stroke-width="2"/>
  <text x="100" y="195" font-size="12" font-weight="bold" fill="#7e22ce">D (${p2}, ${v1})</text>

  <!-- Work Done Banner -->
  <rect x="200" y="115" width="130" height="26" rx="5" fill="#ffffff" stroke="#f59e0b" stroke-width="1.5"/>
  <text x="265" y="132" font-size="11" font-weight="bold" fill="#b45309" text-anchor="middle">Work W = ∮ P dV</text>
</svg>
`;

  return {
    type: 'thermo_pv',
    title: 'Thermodynamic P-V Cyclic Indicator Diagram',
    svgCode: svg.trim(),
    parameters: { p1, v1, p2, v2 },
    labels: ['State A', 'State B', 'State C', 'State D', 'Isobaric Expansion', 'Isochoric Cooling', 'Net Work Done W_net'],
    caption: `Closed cyclic process A → B → C → D → A for an ideal gas with clockwise traversal generating positive mechanical work equivalent to loop area.`
  };
}

function createGeometryDiagram(params: Record<string, any>): DiagramSpec {
  const angle = params.angle || '60°';
  const radius = params.radius || '5 cm';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <rect width="540" height="270" rx="12" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5" />

  <!-- Circle with Center O -->
  <circle cx="280" cy="135" r="85" fill="#f8fafc" stroke="#2563eb" stroke-width="3"/>
  <circle cx="280" cy="135" r="4.5" fill="#1d4ed8"/>
  <text x="290" y="132" font-size="13" font-weight="bold" fill="#1e40af">O</text>

  <!-- External Point P at x=90, y=135 -->
  <circle cx="90" cy="135" r="5" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <text x="68" y="140" font-size="14" font-weight="bold" fill="#dc2626">P</text>

  <!-- Tangents PT1 (top) and PT2 (bottom) -->
  <!-- Tangent contact points T1 at (235, 62), T2 at (235, 208) -->
  <line x1="90" y1="135" x2="245" y2="58" stroke="#dc2626" stroke-width="2.5"/>
  <line x1="90" y1="135" x2="245" y2="212" stroke="#dc2626" stroke-width="2.5"/>

  <!-- Secant PO connecting Center O to External Point P -->
  <line x1="90" y1="135" x2="365" y2="135" stroke="#475569" stroke-width="2" stroke-dasharray="6,4"/>

  <!-- Radii OT1 and OT2 perpendicular to Tangents -->
  <line x1="280" y1="135" x2="235" y2="62" stroke="#16a34a" stroke-width="2.5"/>
  <line x1="280" y1="135" x2="235" y2="208" stroke="#16a34a" stroke-width="2.5"/>

  <!-- Perpendicular Right-Angle Markers at T1 and T2 -->
  <polyline points="239,70 246,66 242,58" fill="none" stroke="#16a34a" stroke-width="2"/>
  <polyline points="239,200 246,204 242,212" fill="none" stroke="#16a34a" stroke-width="2"/>

  <!-- Tangent Points Labels -->
  <circle cx="235" cy="62" r="4.5" fill="#dc2626"/>
  <text x="228" y="48" font-size="13" font-weight="bold" fill="#dc2626">T₁</text>

  <circle cx="235" cy="208" r="4.5" fill="#dc2626"/>
  <text x="228" y="228" font-size="13" font-weight="bold" fill="#dc2626">T₂</text>

  <!-- Radius Label -->
  <rect x="250" y="90" width="55" height="20" rx="4" fill="#f0fdf4" stroke="#bbf7d0" stroke-width="1"/>
  <text x="277" y="104" font-size="11" font-weight="bold" fill="#15803d" text-anchor="middle">r = ${radius}</text>

  <!-- Subtended Angle Arc at Point P -->
  <path d="M 125 125 A 35 35 0 0 1 125 145" fill="none" stroke="#2563eb" stroke-width="2"/>
  <rect x="122" y="110" width="68" height="22" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
  <text x="156" y="125" font-size="10" font-weight="bold" fill="#1d4ed8" text-anchor="middle">∠T₁PT₂ = ${angle}</text>
</svg>
`;

  return {
    type: 'geometry',
    title: 'Circle Tangents & Perpendicular Radii',
    svgCode: svg.trim(),
    parameters: { angle, radius },
    labels: ['Point P', 'Tangents PT₁, PT₂', 'Radius r', 'Center O', 'Right Angle Theorem (OT ⟂ PT)'],
    caption: `Geometry figure showing pair of tangents drawn from external point P to circle with center O and radius ${radius}, subtending angle ${angle}.`
  };
}

function createChemistryDiagram(params: Record<string, any>): DiagramSpec {
  const reagent = params.reagent || 'HNO₃ / H₂SO₄';
  const compound = params.compound || 'Nitrobenzene';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <defs>
    <marker id="rxn-arrow" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#7c3aed"/>
    </marker>
  </defs>

  <rect width="540" height="270" rx="12" fill="#faf5ff" stroke="#e9d5ff" stroke-width="1.5" />

  <!-- Reactant: Benzene Ring (x = 110, y = 135) -->
  <g transform="translate(110, 135)">
    <!-- Hexagon -->
    <polygon points="0,-48 42,-24 42,24 0,48 -42,24 -42,-24" fill="#ffffff" stroke="#0f172a" stroke-width="3.5"/>
    <!-- Delocalized aromatic pi ring -->
    <circle cx="0" cy="0" r="24" fill="none" stroke="#0f172a" stroke-width="2.5" stroke-dasharray="6,4"/>
    <rect x="-35" y="60" width="70" height="22" rx="4" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="0" y="75" font-size="12" font-weight="bold" fill="#0f172a" text-anchor="middle">Benzene</text>
  </g>

  <!-- Reaction Arrow with Reagents and Reaction Conditions -->
  <g transform="translate(220, 135)">
    <line x1="0" y1="0" x2="100" y2="0" stroke="#7c3aed" stroke-width="3" marker-end="url(#rxn-arrow)"/>
    
    <!-- Reagent Badge Above Arrow -->
    <rect x="0" y="-35" width="105" height="24" rx="5" fill="#ffffff" stroke="#c084fc" stroke-width="1.5"/>
    <text x="52" y="-19" font-size="11" font-weight="bold" fill="#6d28d9" text-anchor="middle">${reagent}</text>

    <!-- Condition Below Arrow -->
    <text x="52" y="22" font-size="11" font-weight="bold" fill="#475569" text-anchor="middle">50°C – 60°C</text>
    <text x="52" y="38" font-size="10" font-weight="bold" fill="#059669" text-anchor="middle">Electrophilic Substitution</text>
  </g>

  <!-- Product: Nitrobenzene (x = 420, y = 135) -->
  <g transform="translate(420, 135)">
    <polygon points="0,-48 42,-24 42,24 0,48 -42,24 -42,-24" fill="#ffffff" stroke="#0f172a" stroke-width="3.5"/>
    <circle cx="0" cy="0" r="24" fill="none" stroke="#0f172a" stroke-width="2.5" stroke-dasharray="6,4"/>
    <!-- Substituent NO2 Bond -->
    <line x1="0" y1="-48" x2="0" y2="-75" stroke="#0f172a" stroke-width="3.5"/>
    <rect x="-30" y="-102" width="60" height="26" rx="5" fill="#fee2e2" stroke="#fca5a5" stroke-width="2"/>
    <text x="0" y="-85" font-size="13" font-weight="900" fill="#dc2626" text-anchor="middle">−NO₂</text>
    
    <rect x="-45" y="60" width="90" height="22" rx="4" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="0" y="75" font-size="12" font-weight="bold" fill="#0f172a" text-anchor="middle">${compound}</text>
  </g>
</svg>
`;

  return {
    type: 'chemistry_organic',
    title: 'Electrophilic Aromatic Substitution Reaction',
    svgCode: svg.trim(),
    parameters: { reagent, compound },
    labels: ['Benzene', reagent, compound, 'Nitronium Electrophile NO₂⁺'],
    caption: `Chemical reaction mechanism illustrating aromatic nitration using ${reagent} producing ${compound}.`
  };
}

function createBiologyDiagram(params: Record<string, any>): DiagramSpec {
  const organelle = params.organelle || 'Mitochondria';

  const svg = `
<svg viewBox="0 0 540 270" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto select-none font-sans">
  <rect width="540" height="270" rx="12" fill="#f0fdf4" stroke="#dcfce7" stroke-width="1.5" />

  <!-- Outer Membrane (Elliptical) -->
  <ellipse cx="270" cy="135" rx="200" ry="95" fill="#dcfce7" stroke="#15803d" stroke-width="4"/>
  <ellipse cx="270" cy="135" rx="186" ry="82" fill="#f0fdf4" stroke="#16a34a" stroke-width="2" stroke-dasharray="4,2"/>

  <!-- Inner Membrane Cristae Infoldings -->
  <path d="M 120 135 C 140 100, 160 170, 190 125 C 220 90, 240 175, 270 125 C 300 85, 330 175, 360 125 C 380 90, 410 160, 420 135" fill="none" stroke="#166534" stroke-width="3.5" stroke-linecap="round"/>

  <!-- Mitochondrial Matrix Components: Circular DNA and Ribosomes -->
  <circle cx="230" cy="110" r="9" fill="none" stroke="#ea580c" stroke-width="2.5" stroke-dasharray="3,2"/>
  <circle cx="320" cy="160" r="8" fill="none" stroke="#ea580c" stroke-width="2.5" stroke-dasharray="3,2"/>
  <text x="230" y="98" font-size="10" font-weight="bold" fill="#c2410c" text-anchor="middle">Circular mtDNA</text>

  <!-- ATP Synthase Particle Dots -->
  <circle cx="210" cy="140" r="3" fill="#15803d"/>
  <circle cx="280" cy="145" r="3" fill="#15803d"/>
  <circle cx="350" cy="140" r="3" fill="#15803d"/>

  <!-- Pointer Callout Lines and Labels -->
  <!-- Outer Membrane Callout -->
  <line x1="270" y1="40" x2="330" y2="20" stroke="#166534" stroke-width="1.5"/>
  <rect x="330" y="8" width="125" height="22" rx="4" fill="#ffffff" stroke="#86efac" stroke-width="1"/>
  <text x="392" y="23" font-size="11" font-weight="bold" fill="#14532d" text-anchor="middle">Outer Membrane</text>

  <!-- Inner Cristae Callout -->
  <line x1="290" y1="125" x2="350" y2="90" stroke="#166534" stroke-width="1.5"/>
  <rect x="350" y="78" width="145" height="22" rx="4" fill="#ffffff" stroke="#86efac" stroke-width="1"/>
  <text x="422" y="93" font-size="11" font-weight="bold" fill="#15803d" text-anchor="middle">Cristae (ETC Complexes)</text>

  <!-- Matrix Callout -->
  <line x1="250" y1="150" x2="180" y2="185" stroke="#166534" stroke-width="1.5"/>
  <rect x="80" y="175" width="135" height="22" rx="4" fill="#ffffff" stroke="#86efac" stroke-width="1"/>
  <text x="147" y="190" font-size="11" font-weight="bold" fill="#166534" text-anchor="middle">Mitochondrial Matrix</text>

  <!-- Title Badge at Bottom -->
  <rect x="160" y="235" width="220" height="24" rx="5" fill="#ffffff" stroke="#15803d" stroke-width="1.5"/>
  <text x="270" y="251" font-size="12" font-weight="bold" fill="#14532d" text-anchor="middle">Ultrastructure: ${organelle}</text>
</svg>
`;

  return {
    type: 'biology_cell',
    title: 'Ultrastructure of Semi-Autonomous Organelle',
    svgCode: svg.trim(),
    parameters: { organelle },
    labels: ['Outer Membrane', 'Inner Membrane', 'Cristae Infoldings', 'Matrix', 'Circular mtDNA', 'Ribosomes'],
    caption: `Diagram illustrating double-membrane organization of ${organelle}, cristae surface area expansion for ATP synthase, and matrix containing Krebs cycle enzymes.`
  };
}

