import { StudentRegistration } from '../types';

export const INITIAL_STUDENTS: StudentRegistration[] = [
  {
    id: 'stud-001',
    name: 'Rohan Verma',
    email: 'rohan.verma@student.edu',
    rollNumber: 'JEE-2026-0412',
    targetExam: 'JEE Advanced',
    grade: 'Class 12',
    phone: '+91 98765 43210',
    registeredAt: '2026-08-14T09:30:00Z',
    status: 'verified',
    avatarInitials: 'RV',
    testsCompleted: 4,
    averageScore: 84,
    highestScore: 96,
    notes: 'Exceptional in rotational dynamics and circuit problems. Needs review on organic reaction stereochemistry.',
    recentAttempts: [
      {
        id: 'att-101',
        testTitle: 'JEE Advanced Physics & Circuit Mechanics',
        subject: 'Physics',
        score: 16,
        maxScore: 16,
        accuracy: 100,
        completedAt: '2026-09-02T14:20:00Z',
        attemptedQuestions: [
          {
            questionId: 'q-phys-01',
            questionText: 'Equivalent resistance of the bridge resistor network...',
            selectedOption: 'B',
            correctOption: 'B',
            isCorrect: true,
          },
          {
            questionId: 'q-phys-02',
            questionText: 'Acceleration and string tension of inclined plane block...',
            selectedOption: 'B',
            correctOption: 'B',
            isCorrect: true,
          },
        ],
      },
      {
        id: 'att-102',
        testTitle: 'Full Length JEE Main Mock Test',
        subject: 'Physics',
        score: 12,
        maxScore: 16,
        accuracy: 75,
        completedAt: '2026-08-28T11:00:00Z',
        attemptedQuestions: [
          {
            questionId: 'q-phys-01',
            questionText: 'Equivalent resistance of the bridge resistor network...',
            selectedOption: 'B',
            correctOption: 'B',
            isCorrect: true,
          },
        ],
      },
    ],
  },
  {
    id: 'stud-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@aims.edu',
    rollNumber: 'NEET-2026-1089',
    targetExam: 'NEET',
    grade: 'Class 12',
    phone: '+91 98451 22345',
    registeredAt: '2026-08-18T10:15:00Z',
    status: 'verified',
    avatarInitials: 'PS',
    testsCompleted: 6,
    averageScore: 88,
    highestScore: 94,
    notes: 'Top tier biological cell organelles and plant physiology knowledge. Consistently finishes tests with high speed.',
    recentAttempts: [
      {
        id: 'att-103',
        testTitle: 'NEET Biology Cytology & Genetics Mock',
        subject: 'Biology',
        score: 16,
        maxScore: 16,
        accuracy: 100,
        completedAt: '2026-09-03T16:45:00Z',
        attemptedQuestions: [
          {
            questionId: 'q-bio-01',
            questionText: 'Oxidative phosphorylation and ATP synthesis sites in mitochondria...',
            selectedOption: 'C',
            correctOption: 'C',
            isCorrect: true,
          },
        ],
      },
    ],
  },
  {
    id: 'stud-003',
    name: 'Aarav Patel',
    email: 'aarav.patel@school.org',
    rollNumber: 'JEE-2026-0773',
    targetExam: 'JEE Main',
    grade: 'Class 11',
    phone: '+91 97123 45678',
    registeredAt: '2026-08-25T14:40:00Z',
    status: 'active',
    avatarInitials: 'AP',
    testsCompleted: 3,
    averageScore: 72,
    highestScore: 80,
    notes: 'Strong in kinematics and graph interpretations. Recommended additional practice on thermodynamics P-V cycles.',
    recentAttempts: [
      {
        id: 'att-104',
        testTitle: 'Mechanics & Graph Analysis Test',
        subject: 'Physics',
        score: 8,
        maxScore: 12,
        accuracy: 66,
        completedAt: '2026-09-01T09:15:00Z',
        attemptedQuestions: [],
      },
    ],
  },
  {
    id: 'stud-004',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@jeeprep.net',
    rollNumber: 'JEE-2026-0925',
    targetExam: 'JEE Advanced',
    grade: 'Dropper/Repeater',
    phone: '+91 99887 76655',
    registeredAt: '2026-08-10T08:00:00Z',
    status: 'verified',
    avatarInitials: 'AI',
    testsCompleted: 5,
    averageScore: 92,
    highestScore: 100,
    notes: 'Rank contender (< 500 AIR expected). Rapid problem solver with deep geometric and calculus understanding.',
    recentAttempts: [
      {
        id: 'att-105',
        testTitle: 'JEE Advanced Mathematics & Physics Combo',
        subject: 'Mathematics',
        score: 20,
        maxScore: 20,
        accuracy: 100,
        completedAt: '2026-09-04T12:00:00Z',
        attemptedQuestions: [],
      },
    ],
  },
  {
    id: 'stud-005',
    name: 'Kabir Sen',
    email: 'kabir.sen@medicalaspirants.in',
    rollNumber: 'NEET-2026-1204',
    targetExam: 'NEET',
    grade: 'Class 11',
    phone: '+91 91234 56789',
    registeredAt: '2026-09-01T11:20:00Z',
    status: 'pending',
    avatarInitials: 'KS',
    testsCompleted: 2,
    averageScore: 65,
    highestScore: 72,
    notes: 'Newly registered student. Awaiting teacher document verification and baseline diagnostics.',
    recentAttempts: [],
  },
];
